### PR TITLE
fix flickering v3

### PR DESCRIPTION
**Pull request by sevz17**
This mitigate the issue mentioned [here](https://github.com/djpohly/dwl/pull/357#issuecomment-1352518941) and also is shorter than #357

### CODE REVIEW

**Comment by BenJarg** [comment]
I'm still seeing an issue like the one you mentioned in #357. For example, starting a client, putting it in another tag by itself, then run `kill -STOP PID` on the process, when I try to switch to the tag with the stopped window, dwl doesn't update until switching to a different tag.

**Comment by sevz17** [comment]
> I'm still seeing an issue like the one you mentioned in #357. For example, starting a client, putting it in another tag by itself, then run `kill -STOP PID` on the process, when I try to switch to the tag with the stopped window, dwl doesn't update until switching to a different tag.

Yep, that's why I said "mitigate", there is no easy way to do not skip frames if the client is stopped.

**Comment by sevz17** [comment]
I think I won't merge this or #357 for 0.4

**Comment by sevz17** [comment]
@BenJarg, @Job79, @maxagabb, can you try this?, I was able to deal with stopped clients.

**Comment by maxagabb** [comment]
On this PR I was able to replicate the stopped client issue (dwl not updating) with BenJarg's steps using ` kill -STOP PID `

On main branch the behavior is different. dwl updates but the stopped client is not sized correctly;

**Comment by sevz17** [comment]
> On this PR I was able to replicate the stopped client issue (dwl not updating) with BenJarg's steps using `kill -STOP PID`

Very odd, FWIW it works fine to me.

> On main branch the behavior is different. dwl updates but the stopped client is not sized correctly

That's the expected (and only possible) behavior, the client can do nothing.

**Comment by maxagabb** [comment]
Yup could be an issue with how I'm testing. I tried removing all files in .gitignore and compiling again.

I use an alacritty window to send STOP to foot after sending foot to another tag.

Issue does not happen if I go the foot tag once before sending STOP from alacritty.

**Comment by sevz17** [comment]
> Yup could be an issue with how I'm testing. I tried removing all files in .gitignore and compiling again.
> 
> I use an alacritty window to send STOP to foot after sending foot to another tag.
> 
> Issue does not happen if I go the foot tag once before sending STOP from alacritty.

It should be fixed now.

**Comment by maxagabb** [comment]
Cool I confirmed this fixes the issue for me. 

I noticed there's flicker with foot terminals only when spawning them with bemenu (spawning and resizing).

When launched with keyboard shortcut they only flicker when spawned (no flicker on resize).

**Comment by Job79** [comment]
Am testing this patch on my local dwl, seems to work fine so far. Never experienced issues with clients freezing when stopped, does this issue only occur when using `kill -STOP {pid}`?

**Comment by maxagabb** [comment]
> Am testing this patch on my local dwl, seems to work fine so far. Never experienced issues with clients freezing when stopped, does this issue only occur when using `kill -STOP {pid}`?

Yep I believe that issue only came from `kill -STOP {pid}`, no freezes otherwise

**Comment by sevz17** [comment]
Yep, for processes where dwl is not their parent (bemenu makes double fork, which means that the created process is child of init) we assume that they are stopped (because we can't get their info), otherwise we could end up with a frozen display.

**Comment by maxagabb** [comment]
I'm getting no flicker from alacritty windows now using the shortcut. 

The desktop background appears briefly when spawning them, but there's no flicker on second monitor (which happened before this PR). 

I'm seeing no issues at all when resizing.

**Comment by BenJarg** [comment]
@sevz17 The stopped client issue looks resolved for me as well.

**Pull request closed without merging**
