### PR TITLE
fix undeclared WLR_KEY_PRESSED

### PR DESCRIPTION
**Pull request by richardipsum**
hi, not sure if this is correct or not, but I was unable to compile latest dwl with latest wlroots, this patch is a total guess, but dwl is at least running on my system now

thanks,
richard

### CODE REVIEW

**Comment by guidocella** [comment]
This is correct, WLR_KEY_PRESSED was replaced in https://github.com/swaywm/wlroots/pull/2446

**Comment by djvs** [comment]
I was about to PR this myself.  This is definitely correct, please merge

**Comment by djvs** [comment]
@djpohly need a second maintainer?

**Comment by djpohly** [comment]
Thanks for the fix!

**Comment by djpohly** [comment]
@djvs Also, if that's an offer, yes, I'm looking to build a team so development can continue more smoothly!  Let me know!

**Comment by djvs** [comment]
Start a discord maybe?

**Comment by djpohly** [comment]
Great idea!  Thanks!

**Pull request merged**
