### PR TITLE
fix flickering v2

### LINKED ISSUE #306: Flickering when modifying main area's ratio
## Info
dwl's commit: ba7dcb2dea2d5dc46b73b6b9194daab94a325a05 (master at time of writing, but also happens with the v0.3.1 release)
wlroots version: 0.15.1
## Description

There is noticeable flickering when resizing the ratio of the main area. I'm using the default config, with no patches or modifications. Not shown in the video is the flicker overflowing onto the next display on the right, when increasing the ratio.

https://user-images.githubusercontent.com/83099052/190829920-942f20ae-b38f-4e21-92ce-4155a23ab40a.mp4

Note that the above video happens to show dwl running inside another compositor, but the exact same thing happens when running it standalone.

Thanks

### PR DESCRIPTION
**Pull request by sevz17**
Alternative to #350.

Fixes #306

### CODE REVIEW

**Comment by sevz17** [comment]
@Job79, this fixes the flickering with Alacritty, seems like this doesn't cause freezes, I will test during the next days, can you test too?

**Comment by Job79** [comment]
Just applied the diff to my local setup, all seems to work fine so far. Will report back when I experience any problems during the next days. Thanks for working on these patches, been daily driven dwl for 6 months now and am really liking it.

**Comment by Job79** [comment]
Can confirm the issue with Xwayland applications when using these changes. When using phpstorm(Xwayland application) the buttons in the menu bar no longer work. They works fine when using the previous "fix flickering" PR.

**Comment by maxagabb** [comment]
This PR feels really nice! Flickering in alacritty still feels fully resolved with https://github.com/djpohly/dwl/commit/a9b1fbf652ad4657d4c7013ee3238bedb691408c reverted. Xwayland menus also work again.

Alternatively re-enabling scene node inside #ifdef also fixes Xwayland menus when I test:
```
#ifdef XWAYLAND
	/* Handle unmanaged clients first so we can return prior create borders */
  wlr_scene_node_set_enabled(&c->scene->node, 1);
```

**Comment by sevz17** [comment]
> This PR feels really nice! Flickering in alacritty still feels fully resolved with [a9b1fbf](https://github.com/djpohly/dwl/commit/a9b1fbf652ad4657d4c7013ee3238bedb691408c) reverted. Xwayland menus also work again.

That commit is meant to fix flickering when mapping clients.

> Alternatively re-enabling scene node inside #ifdef also fixes Xwayland menus when I test:
> 
> ```
> #ifdef XWAYLAND
> 	/* Handle unmanaged clients first so we can return prior create borders */
>   wlr_scene_node_set_enabled(&c->scene->node, 1);
> ```

I pushed an alternative solution to only disable the node for XDG clients.

**Comment by sevz17** [comment]
Also, I found a freeze when running a nested dwl and it is stopped (e.g because you are debugging it ) the host dwl will freeze when switch to another tag and then switch back.

I'll try a v3 of this, the problem above probably never will happen to normal users but I constantly have to debug dwl, and honestly I don't want to merge this in this state, even if it fixes the flickering.

**Comment by maxagabb** [comment]
Makes a lot of sense, also thanks for all the improvements! I'm having great time daily driving dwl.

**Comment by sevz17** [comment]
Superseded by #363

**Pull request closed without merging**
