### PR TITLE
misc fixes/changes in wlroots-next

### PR DESCRIPTION
**Pull request by sevz17**
Just a few fixes/changes which I'm too lazy to separate and do a proper PR

some of these can be a applied to main, but... meh, who cares?

### CODE REVIEW

**Comment by sevz17** [comment]
Sadly this does not fix the wrong initial size of some clients (I only experienced issues with some GTK apps)

**Comment by sevz17** [comment]
The gamma bits were separated into #516

**Comment by sevz17** [comment]
If nobody has a complain, I'll merge this tomorrow around this time.

**Comment by fictitiousexistence** [comment]
I got this when trying to build:

```
In file included from dwl.c:396:
client.h: In function ‘client_activate_surface’:
client.h:103:25: error: implicit declaration of function ‘wlr_xdg_toplevel_try_from_wlr_surface’; did you mean ‘wlr_xdg_surface_try_from_wlr_surface’? [-Werror=implicit-function-declaration]
  103 |         if ((toplevel = wlr_xdg_toplevel_try_from_wlr_surface(s)))
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                         wlr_xdg_surface_try_from_wlr_surface
client.h:103:23: warning: assignment to ‘struct wlr_xdg_toplevel *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  103 |         if ((toplevel = wlr_xdg_toplevel_try_from_wlr_surface(s)))
      |                       ^
dwl.c: In function ‘resize’:
dwl.c:1952:9: error: implicit declaration of function ‘wlr_scene_subsurface_tree_set_clip’; did you mean ‘wlr_scene_subsurface_tree_create’? [-Werror=implicit-function-declaration]
 1952 |         wlr_scene_subsurface_tree_set_clip(&c->scene_surface->node, &clip);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         wlr_scene_subsurface_tree_create
dwl.c: In function ‘createmon’:
dwl.c:932:9: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
  932 |         strncpy(m->ltsymbol, m->lt[m->sellt]->symbol, LENGTH(m->ltsymbol));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dwl.c: In function ‘arrange’:
dwl.c:460:9: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
  460 |         strncpy(m->ltsymbol, m->lt[m->sellt]->symbol, LENGTH(m->ltsymbol));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
dwl.c: In function ‘setlayout’:
dwl.c:2094:9: warning: ‘strncpy’ specified bound 16 equals destination size [-Wstringop-truncation]
 2094 |         strncpy(selmon->ltsymbol, selmon->lt[selmon->sellt]->symbol, LENGTH(selmon->ltsymbol));
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make: *** [Makefile:66: dwl.o] Error 1
```

**Comment by sevz17** [comment]
Did you update wlroots?

**Comment by fictitiousexistence** [comment]
Yeah. Tried building before and then after updating.


Was on wlroots commit f750c744 due to an issue related to dwl/bemenu/wlroots?
https://github.com/Cloudef/bemenu/issues/370

I'm on gentoo, using the 9999 package, rebuilt that and then tried making dwl again.

Nov 19, 2023 11:53:12 PM Leonardo Hernández ***@***.***>:

**Comment by sevz17** [comment]
Are you sure you updated it? wlr_scene_subsurface_tree_set_clip was added [in this commit](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/3d3cca9164106212a8c6e52125bb05c18ada70a7) and wlr_xdg_toplevel_try_from_wlr_surface in [this one](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/319e4125ab699c2346c7d1b66ff8d06064ec6ac2), I'm also on gentoo, I use dwl-9999-r1 and wlroots-9999 and no problems here.

**Comment by fictitiousexistence** [comment]
@sevz17 
I was sure till you asked haha

I re-emerged wlroots, wayland, and wayland-protocols.
Also installed using the specific commit:
`export EGIT_COMMIT="3d3cca91" && emerge --ask --verbose wlroots`


I have to run
`export EGIT_COMMIT="f750c744" && emerge --ask --verbose wlroots`
Cause anything past that commit makes both bemenu and swaybg crash even when run inside sway. 

I don't use the gentoo dwl package I just 
`git clone https://github.com/djpohly/dwl.git --branch wlroots-next` and build.

**Comment by fictitiousexistence** [comment]
@sevz17
oy vey......

I searched my system for wlr_scene.h

Found 2, ./usr/local/include/wlr/types/wlr_scene.h & /usr/include/wlr/types/wlr_scene.h

I removed /usr/local/include/wlr & /usr/local/include/hyprland and then I was able to build no issue. 

Whoops....

**Pull request merged**
