### PR TITLE
fix flickering

### PR DESCRIPTION
**Pull request by sevz17**
Before merging, make sure #349 is fixed.

Fixes: #306

### CODE REVIEW

**Comment by sevz17** [comment]
@Job79, @PalanixYT, can you test this?

**Comment by Job79** [comment]
Can no longer reproduce the "freeze" issue from #349 when applying this pull request

**Comment by Job79** [comment]
Have been using this patch for 2 days now, never experienced any freezes. But I did see some flickering when resizing / opening alacritty. There is no flickering when using foot / chromium, so this is probably an alactitty problem?

**Comment by sevz17** [comment]
> Have been using this patch for 2 days now, never experienced any freezes. But I did see some flickering when resizing / opening alacritty. There is no flickering when using foot / chromium, so this is probably an alactitty problem?

Not really, this is hackish, we should listen to the `commit` event, not `ack_configure`, but some clients do not call wl_surface.commit when we resize them with the same size (and this is ok, they are not obligated to do it), wl_surface.commit must be called after submitting a new buffer (e.g because it changed its size, its content, etc), `ack_configure` is just to let us know that they received the configure (new size) event (at this moment they aren't obligated to submit a new buffer)

**Comment by sevz17** [comment]
Superseded by #357 and #363

**Pull request closed without merging**
