### PR TITLE
fix flickering when resizing windows

### PR DESCRIPTION
**Pull request by sevz17**
based on the @PalanixYT fix.

### CODE REVIEW

**Comment by sevz17** [comment]
Cannot reproduce the firefox freeze with `WLR_WL_OUTPUTS=2`

**Comment by PalanixYT** [comment]
Please remember to remove the comment in commitnotify. I will test the pr on new 0.4r1 too.

**Comment by PalanixYT** [comment]
I can no longer confirm the firefox freeze with 0.4r1. Perhaps it was a problem with wlroots 0.15? I am not sure.

**Comment by sevz17** [comment]
> Please remember to remove the comment in commitnotify. I will test the pr on new 0.4r1 too.

Done

**Pull request merged**
