### PR TITLE
add dwl(1)

### PR DESCRIPTION
**Pull request by Humm42**
Documentation is good.  Man pages are documentation.  A program without
a man page is worthless.

### CODE REVIEW

**Comment by Sevz17** [comment]
Mmm, `dwl.1` should be in the root directory like in dwm

**Comment by Sevz17** [comment]
Mmm, `dwl.1` should be in the root directory like in dwm

**Comment by Sevz17** [comment]
Consider adding this to the examples section
```roff
Do not start anything but close stdin:
.Dl dwl -s 'exec <&-'
```

**Comment by Humm42** [comment]
>Consider adding this to the examples section
>```roff
>Do not start anything but close stdin:
>.Dl dwl -s 'exec <&-'
>```

Why would you do that?

**Comment by Sevz17** [comment]
> Why would you do that?

Well, maybe I am biased because I test changes before committing them and I don't want my terminal to get spammed by dwl status.
But you are right a normal user usually wants a status bar and/or start something

**Comment by Sevz17** [comment]
All manpages I have on my system (including dwm) start with `.TH`, why this doesn't have it?

**Comment by Humm42** [comment]
>All manpages I have on my system (including dwm) start with `.TH`, why this doesn't have it?

There are two macro sets for man pages in use today: -man and -mdoc. -man was introduced in v7; -mdoc later in BSD. Today, both are used widely. You’ll see -mdoc macros being used especially in programs having some relation to the BSDs. Take a look at, for example, (LibreSSL’s) ssl(3), bmake(1), mandoc(1). For documentation for -man and -mdoc, see mandoc’s man(7) and mdoc(7) or groff’s groff_man(7) and groff_mdoc(7). For an introduction to -mdoc and a *History of UNIX Manpages*, see <https://manpages.bsd.lv/>.

dwl(1) uses -mdoc. dwm(1) uses -man. Both are usable on the major modern Unices.

**Comment by Sevz17** [comment]
Thanks!

**Comment by Humm42** [comment]
>Mmm, `dwl.1` should be in the root directory like in dwm

Sure, though that has nothing to do with dwm.

**Comment by Humm42** [comment]
>All manpages I have on my system (including dwm) start with `.TH`, why this doesn't have it?

There are two macro sets for man pages in use today: -man and -mdoc. 
-man was introduced in v7; -mdoc later in BSD. Today, both are used 
widely. You’ll see -mdoc macros being used especially in programs having 
some relation to the BSDs. Take a look at, for example, (LibreSSL’s) 
ssl(3), bmake(1), mandoc(1). For documentation for -man and -mdoc, see 
mandoc’s man(7) and mdoc(7) or groff’s groff_man(7) and groff_mdoc(7). 
For an introduction to -mdoc and a *History of UNIX Manpages*, see 
<https://manpages.bsd.lv/>.

dwl(1) uses -mdoc. dwm(1) uses -man. Both are usable on the major modern 
Unices.

**Pull request merged**
