### PR TITLE
Add known dwl-specific status bar scripts to README.md

### PR DESCRIPTION
**Pull request by fauxmight**

### CODE REVIEW

**Comment by Sevz17** [comment]
Great idea!
However missing Thanatos' scripts

**Comment by fauxmight** [comment]
@Sevz17 link?

**Comment by Sevz17** [comment]
> @Sevz17 link? (I don't know about his, and cannot seem to find it.)

It is pinned on the discord's customization channel

**Comment by fauxmight** [comment]
Closed in favor of #257 (added Thanatos' scripts [thanks, @Sevz17 ] and squashed commits)

**Pull request closed without merging**
