### PR TITLE
Display clients count in monocle symbol Fix #387

### LINKED ISSUE #387: Count of clients should be visible when on monocle layout
Hi, in DWM the count of clients on given tag is visible when on monocle and there's more than 1 window. Since we want to achieve parity it should be implemented. Also if I recall correctly for  >9 it's `9+`.

### PR DESCRIPTION
**Pull request by yveszoundi**
- Replicate missing functionality from dwl to display the client count in monocle mode
  - Add ltsymbol field to Monitor struct
  - Display client count in monocle mode when greater than zero
- Tested with somebar and dwlb

### CODE REVIEW

**Comment by yveszoundi** [comment]
This addresses issue #387

**Comment by yveszoundi** [comment]
Please let me know if there are any concerns. In case it helps, I added few screenshots with most of the supported status bars.

### Notes

- I've not tried [dtao](https://github.com/djpohly/dtao) as its configuration/usage is not "self-evident" to me, I vaguely recall trying out `dzen` a very long time ago. I assume that dtao consumes dwl printed output just like other bars.
- For [dwl-bar](https://github.com/MadcowOG/dwl-bar), I was never able to try it (empty bar on my system), not sure if it's related to my missing dependencies, musl, etc. I assume that it consumes dwl printed output just like other bars on machines that do render the bar properly.

### Screenshots

#### somebar

somebar

#### dwlb

dwlb

#### yambar (latest git)

yambar

#### waybar

waybar

**Comment by MadcowOG** [comment]
A little unrelated and I don't mean to hijack. I'm sorry dwl-bar didn't work, I already had a commit made, but forgot to push it up. Everything should work now.

I tested and got a screenshot of dwl-bar working with your pr; I can't wait for this to be merged!

**Comment by sevz17** [comment]
Thanks!

**Pull request merged**
