### PR TITLE
double forking for process spawning

### PR DESCRIPTION
**Pull request by Sevz17**
Fixes: #177

### CODE REVIEW

**Comment by djpohly** [comment]
I really don't like double-forking.  It leaves orphaned processes and messes up the process tree.

**Comment by Sevz17** [comment]
Try wlroots-next, Xwayland won't be able to spawn

**Comment by Sevz17** [comment]
> It leaves orphaned processes and messes up the process tree.

We could do something like [this](https://github.com/swaywm/sway/blob/master/sway/commands/exec_always.c#L48-L92) to avoid orphaned processes

**Comment by djpohly** [comment]
Well, I'm still bummed we can't just SIG_IGN the whole thing because of the XWayland fork/wait, but I put together an idea over in #212 which seems to work (and as a bonus, is shorter :grin:).

**Comment by Sevz17** [comment]
Closed in favor of #212

**Pull request closed without merging**
