### PR TITLE
tagcount should have been a #define

### PR DESCRIPTION
**Pull request by bencollerson**
Tagcount should have been set up as a #define rather than a const so it can be used to in array declarations etc.

### CODE REVIEW

**Comment by sevz17** [comment]
I'm sorry for the late reply.

I don't feel like breaking user configuration again, just for external patches.
I know, it's a trivial change, but still I don't think it should be made.

At most, I'm ok with adding a \#define and defining the variable with the macro.

**Comment by sevz17** [comment]
Thanks!

**Comment by neuromagus** [comment]
What I mean too. If u need variable in array length - this is only ```define```, ```const int tagcount``` need a delete. "salt is salty".

**Comment by sevz17** [comment]
Ah yeah, I didn't say it but I'm gonna revert the second commit, but I'll be when doing another change to the config

**Pull request merged**
