### PR TITLE
rework outputmgrapplyortest()

### PR DESCRIPTION
**Pull request by sevz17**
first disable requested monitors, then enable and/or change mode, x and y, etc.
This is mostly what sway does

### CODE REVIEW

**Comment by sevz17** [comment]
I tested and with this I am able to change to a a non-custom mode, when i tried to change to a custom mode dwl segfaults in wlr_output_commit()

**Comment by sevz17** [comment]
> With this I am able to change to a a non-custom mode, if I try to change to a custom mode dwl segfaults in wlr_output_commit()

seems like https://gitlab.freedesktop.org/wlroots/wlroots/-/merge_requests/3641 could fix the segfault setting a custom mode.

**Comment by dimkr** [comment]
> This is mostly what sway does

How about integrating https://github.com/djpohly/dwl/compare/main...dimkr:dwl:fallback.patch?

**Comment by sevz17** [comment]
> > This is mostly what sway does
> 
> How about integrating https://github.com/djpohly/dwl/compare/main...dimkr:dwl:fallback.patch?

I see the use case, however I don't think it should be on the mainline, but I am not strongly opposed to merging it.

Please open a pr, let @djpohly decide if we merge it.

**Pull request merged**
