### PR TITLE
keep floating clients on top

### LINKED ISSUE #75: Avoid overlaping of tiled and floating windows (like dwm)
Screenshot from 2021-01-04 10-42-05

I'm guessing this is now doable as layershell is implemented.

### PR DESCRIPTION
**Pull request by guidocella**
Fixes #75.

### CODE REVIEW

**Comment by guidocella** [comment]
This is the other possible implementation: https://github.com/guidocella/dwl/commit/50c4f500b44bdf377ff8ff300fd2c862613bfc5d

**Comment by djpohly** [comment]
Thanks for working this out! Hard-coding a check for monocle into focusclient and then calling focusclient from monocle seems kind of hack-ish... could that be done more cleanly?

**Comment by guidocella** [comment]
> Hard-coding a check for monocle into focusclient and then calling focusclient from monocle seems kind of hack-ish... could that be done more cleanly?

Note that the check in `focusclient()` isn't because it's called from `monocle()`, but for when you press `MODKEY+{j,k}` while in monocle.

Calling `focusclient()` in `monocle()` is just to avoid a couple of lines for checking if no client is present. It's equivalent to:

```c
Client *sel = selclient();
if (sel) {
    wl_list_remove(&c->slink);
    wl_list_insert(&stack, &c->slink);
}
```

I will switch to this if you find it more explicit.

**Comment by notthewave** [comment]
Just tested the patch and found 1 problem:
- in floating mode, clients are now drawn below the currently active window instead of above.

**Comment by guidocella** [comment]
Fixed.

**Comment by notthewave** [comment]
Not sure if that's much of a problem, but when cycling through windows, it goes through them in the order in which they were spawned and not in the order in which they are arranged. Not sure how DWM does this.

**However, this is probably out of scope of this pr as this also happens in floating mode.**

**Pull request closed without merging**
