### PR TITLE
fix spelling + remove unecersarry spaces

### PR DESCRIPTION
**Pull request by godalming123**
This fixes a spelling and grammar issue I noticed while browsing the code. It also removes several places where their should only be 1 space instead of 2.

### CODE REVIEW

**Comment by sevz17** [comment]
Fix the indentation please. We use tabs instead of spaces.

**Comment by pm4rcin** [comment]
@godalming123 if you fix small things like that could you also trim the trailing whitespaces [here](https://github.com/djpohly/dwl/blob/f8373ccf2581fa481602bbb7528ba8871f6d5c85/config.def.h#L69-L71)?
Btw. @sevz17 maybe it's a good idea to create .editorconfig for dwl?

**Comment by godalming123** [comment]
I have replaced the spaces with tabs and also removed several places in the source coce where their are 2 spaces which should be 1

**Comment by sevz17** [comment]
Thanks!

**Pull request merged**
