### PR TITLE
use sigaction(2) for signal handling

### PR DESCRIPTION
**Pull request by sevz17**
which means replace signal(2) with sigaction(2)

TODO: find a better description

### CODE REVIEW

**Comment by djpohly** [comment]
Rationale for the original: dwm does it.

**Comment by sevz17** [comment]
> Rationale for the original: dwm does it. (Just as a note, not that I disagree with the change. 

Yes, they are discussing it in their [mailing list](https://lists.suckless.org/hackers/2207/18405.html); after reading [signal(2)](https://man7.org/linux/man-pages/man2/signal.2.html) I think we should switch to [sigaction(2)](https://man7.org/linux/man-pages/man2/sigaction.2.html) (primarily because we ignore SIGPIPE) but nobody has reported problems because that, so we could wait to see what dwm devs do.

**Comment by sevz17** [comment]
Alternatively we can use the wayland helper: `wl_event_loop_add_signal()`

**Comment by sevz17** [comment]
@djpohly, dwm started using sigaction() recently, I will wait two weeks in case they revert the commit or if you want to say something, if not I will merge this on Feb 13th.

**Pull request merged**
