### PR TITLE
add clang-format'ing

### PR DESCRIPTION
**Pull request by ayham-1**
Tried to imitate the current styling as much as possible.

This commit applies the formatting to all `.c` files.

### CODE REVIEW

**Comment by djpohly** [comment]
Hi ayham-1, and thanks for offering your contribution.  The dwl code already adheres to consistent code style guidelines (intentionally matching those used by dwm), and I don't see a reason to make a sweeping formatting change affecting over 2,300 lines of code.  You are free to reformat your own copy of the code as you like for viewing and hacking, but any contributions to the main codebase should match the existing coding style.

**Comment by ayham-1** [comment]
Hello, 
I think you misunderstood what this PR is for.

My intentions were not to create a new formatting, but rather to create a .clang-format configuration file which matches the current styling.

Using clang-format would ensure that this project does actually maintain its styling and commits like [c69a2be](https://github.com/djpohly/dwl/commit/c69a2bec3ff417fbc4ea8fec0a49096773e01e7d) would be unnecessary.

**Comment by sevz17** [comment]
> My intentions were not to create a new formatting, but rather to create a .clang-format configuration file which matches the current styling.

Actually this pr changes tabs to spaces, which obviously doesn't follow our coding style.

**Comment by ayham-1** [comment]
> > My intentions were not to create a new formatting, but rather to create a .clang-format configuration file which matches the current styling.
> 
> Actually this pr changes tabs to spaces, which obviously doesn't follow our coding style.

Is there a style guidance present which I can follow that I am missing? I kinda had to guess while writing the configuration.

**Pull request closed without merging**
